name: Python Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: "0 18 * * *" # Run at 6:00 PM UTC every day

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -e .[test]

      - name: Run tests
        run: pytest

      - name: Upload Scrapy Log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: scrapy-test-log
          path: test-run.log

      - name: Notify Slack on failure
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: Python tests failed in the GitHub Actions workflow!
          author_name: GitHub Actions
          fields: repo,message,commit,author,action,eventName,ref,workflow
